name: rust-toolchain

on:
  pull_request:
    paths:
      - rust-toolchain
      - "*.dockerfile"
      - .devcontainers/Dockerfile
      - .github/workflows/toolchain.yml

permissions:
  contents: read

env:
  YQ_VERSION: v4.2.0

jobs:
  dockerfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - run: |
          ex=0
          for f in $(find . -name Dockerfile -or -name \*.dockerfile); do
            versions=$(sed -nE 's/^ARG RUST_VERSION=([^ ]+)/\1/p' $f)
            if [ -z "$versions" ]; then
              echo "::error file=$f::$f missing `RUST_VERSION` argument"
              ex=$((ex + 1))
            fi
            for mismatch in $(echo "$version" | grep -vF "$(cat rust-toolchain)" || true) ; do
              echo "::error file=$f::$f uses incorrect rust version(s): $mismatch"
              ex=$((ex + 1))
            done
          done
          exit $ex

  workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - run: |
          curl --proto '=https' --tlsv1.3 -vsSfLo /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" \
            && chmod +x /usr/local/bin/yq
      - run: |
          ex=0
          for f in $(find .github/workflows -name '*.yml') ; do
            echo "# $f"
            for image in $(yq eval '.jobs[].container.image' $f) ; do
              if [[ "$image" =~ "^docker://(docker.io/library/)?rust:" ]]; then
                v="${${image##*rust:}%%-*}"
                if [[ "$v" != "$(cat rust-toolchain)" ]]; then
                  echo "::warning file=$f::$f uses incorrect rust version: $v"
                  ex=$((ex + 1))
                fi
              fi
            done
          done
          exit $ex
